name = "App-crypt"
# badges = ["travis-ci.com"]
module_maker="ModuleBuildTiny"
static_install = "auto"
license="perl_5"
authors_from="lib/App/crypt.pm"
[release]
do_not_upload_to_cpan=true
branch="main"
